# Default values for kubestronaut-predictor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
fastapi:
  repository: lfarizav/kubestronautfastapi
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "d8c721f" # {"$imagepolicy": "kubestronaut_predictor:kubestronaut_predictor-policy:tag"}
streamlit:
  repository: lfarizav/kubestronautstreamlit
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "d8c721f" # {"$imagepolicy": "kubestronaut_predictor:kubestronaut_predictor-policy:tag"}

servicefastapi:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8000
  targetPort: 8000
  nodePort: 30100
servicestreamlit:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: NodePort
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8501
  targetPort: 8501
  nodePort: 30000
