apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubestronautfastapi
  name: kubestronautfastapi
spec:
  ports:
  - name: "8000"
    nodePort: {{ .Values.servicefastapi.nodePort }}
    port: {{ .Values.service_fastapi.port }}
    protocol: TCP
    targetPort: {{ .Values.servicefastapi.targetPort }}
  selector:
    app: kubestronautfastapi
  type: NodePort
status:
  loadBalancer: {}
